name: Test & Publish Monorepo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        run: pnpm vitest run --coverage

      - name: Check global coverage
        run: |
          COVERAGE=$(npx c8 check-coverage --lines 95 --functions 95 --branches 95 --statements 95 || echo "fail")
          if [ "$COVERAGE" = "fail" ]; then
            echo "Coverage below 95%"
            exit 1
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  publish:
    name: Publish Packages
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all packages
        run: pnpm -r run build

      - name: Publish each package
        run: pnpm -r publish --access public --no-git-checks --filter=!./**/private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}